name: 📝 Assign Task
description: Assign a new task (Dev Team Only)
type: "Task"

body:

  - type: markdown
    attributes:
      value: |
        🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟
        🐟🐳 DEV TEAM ONLY 🐳🐟
        🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟
        This is a template for the development team to assign a new task.
        If you are not a member of the team, please do not use this template.

  - type: textarea
    id: task
    attributes:
      label: Tasks
      value: |
        Task summary
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Other
      description: Please add any additional sections here and remove the ones you don't need.
      value: |
        ### Details

        ### Questions

        ### References

        ### Notes
